controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /manager

# Redirect root path to manager
root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: "app_dashboard"
        permanent: true

api_login_check:
    path: /manager/api/login_check
