nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["*"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/manager/api":
            allow_origin:
                [
                    "http://localhost",
                    "http://localhost:4200",
                    "http://localhost:3000",
                    "https://projet-fil-rouge-guiback0-qa.up.railway.app",
                    "https://projet-fil-rouge-guiback0-production.up.railway.app",
                ]
            allow_headers: ["Content-Type", "Authorization"]
            allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
            max_age: 3600
