# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ACCESS MNS Frontend CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ 'access_mns_client/**' ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ 'access_mns_client/**' ]


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./access_mns_client

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'access_mns_client/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint --if-present

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Build application
      run: npm run build --if-present

  build-production:
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: ./access_mns_client

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'access_mns_client/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build -- --configuration=production

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: access_mns_client/dist/
        retention-days: 7